---
- name: Install_MariaDB_Server
  ansible.builtin.apt:
    name: mariadb-server
    state: present

- name: Start_MariaDB_service
  ansible.builtin.systemd:
    name: mariadb
    enabled: yes
    state: started
 

- name: Create_WordPress_database
  community.mysql.mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "123456"

- name: Create_WordPress_user
  mysql_user:
    name: "root"
    password: "123456"
    priv: "wordpress.*:ALL"
    state: present
    login_user: root
    login_password: ""
