---
- name: Install_MariaDB_Server
  ansible.builtin.apt:
    name: mariadb-server
    state: present

- name: Start_MariaDB_service
  ansible.builtin.systemd:
    name: mariadb
    enabled: yes
    state: started

- name: Secure_MariaDB
  mysql_secure_installation:
    login_password: ''
    new_password: "{{ db_user }}"
    user: root
    name: "{{ db_user }}"
    login_host: localhost
    hosts: ['localhost', '127.0.0.1', '::1']
    change_root_password: true
    remove_anonymous_user: true
    disallow_root_login_remotely: true
    remove_test_db: true
    register: secure

- debug:
        var: secure    

- name: Create_WordPress_database
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "{{ db_password }}"

- name: Create_WordPress_user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "wordpress.*:ALL"
    state: present
    login_user: root
    login_password: "{{ db_password }}"
