---
- name: Ensure jail.local file exists
  ansible.builtin.file:
    path: /etc/fail2ban/jail.local
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Append Apache and MariaDB auth filters to jail.local
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.local
    block: |
      [apache-auth]
      enabled  = true
      filter   = apache-auth
      action   = iptables[name=apache-auth, port=http, protocol=tcp]
      logpath  = /var/log/apache*/*error.log
      maxretry = 3

      [mariadb-auth]
      enabled  = true
      filter   = mariadb-auth
      action   = iptables[name=mariadb-auth, port=mysql, protocol=tcp]
      logpath  = /var/log/mysql/mysql.log
      maxretry = 3
    state: present

- name: Restart Fail2Ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
